### PR TITLE
Update forecasting-the-stock-market.ipynb

### PR DESCRIPTION
**Pull request by mridulrb**
@sanjeevghimire Installing fbprophet using conda takes more time and has AttributeError, using pip it reduces the installation time, and no errors are generated.  I have attached the screenshot for your reference. 
Screen Shot 2020-08-11 at 3 49 44 PM

### CODE REVIEW

**Comment by Zivilevs** [comment]
Hello @mridulrb, @sanjeevghimire,

I have the same issue, but even after pip install of fbprophet, the AttributeError persists.


```
AttributeError: 'property' object has no attribute '__name__'
```
**Error image**
image


Thank you!

**Comment by mridulrb** [comment]
Hi @Zivilevs 
I had this issue earlier, it was fixed by selecting Default Python 3.6 S (4 vCPU and 16 GB RAM) as runtime. Let me know if it works for you.

**Comment by Zivilevs** [comment]
Hi, @mridulrb,

thank you! It worked!

**Comment by mridulrb** [comment]
Hi @vnderlev & @sanjeevghimire,

Can you verify this request and merge it to the base branch?

**Pull request merged**
